# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef9a801d20a30d3b32e6ffc2fcce7d91867a2a44e17d8ddaf5ab19afe0600de3fa64f0177caf70209e36e2e1ccccb08ce7f44673f03ed72ed7a1369747faf2c8

test:
  secret_key_base: 83fbfebd046cb57e84ad5bcbc8a6ed9aa7c92be5f0c5e3247755dd366f6f8c0a7751d090d4656f4d629a15d851e0ac6fed382667e6f8f8d0a90541cc92ea0d16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
